# Generated by Django 3.2 on 2022-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_tags',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('django', 'django')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_value',
            field=models.IntegerField(default=0),
        ),
    ]
