# Generated by Django 3.2 on 2022-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220408_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_value',
            field=models.IntegerField(),
        ),
    ]
