# Generated by Django 3.2 on 2022-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220409_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
