# Generated by Django 3.2 on 2022-04-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='fact',
        ),
    ]
