# Generated by Django 3.2 on 2022-04-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
