# Generated by Django 3.2 on 2022-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_testimonials_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('education_degree', models.CharField(max_length=50)),
                ('education_year', models.CharField(max_length=50)),
                ('education_university', models.CharField(max_length=50)),
                ('about_education', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_degree', models.CharField(max_length=50)),
                ('experience_year', models.CharField(max_length=50)),
                ('experience_university', models.CharField(max_length=50)),
                ('about_experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=50)),
                ('about_person', models.TextField(max_length=50)),
                ('person_address', models.CharField(max_length=50)),
                ('person_phone', models.CharField(max_length=50)),
                ('persone_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
