# Generated by Django 3.2 on 2022-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_education_professional_experience_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_experience',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
