# Generated by Django 3.2 on 2022-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_professional_experience_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_experience',
            name='about_experience',
            field=models.TextField(max_length=50),
        ),
    ]
