# Generated by Django 3.2 on 2022-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_summary_about_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='about_education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professional_experience',
            name='about_experience',
            field=models.TextField(),
        ),
    ]
