# Generated by Django 3.2 on 2022-04-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_persone_email_summary_person_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professional_Experience',
            new_name='Experience',
        ),
    ]
