# Generated by Django 3.2 on 2022-04-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220410_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='album',
            name='album_subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
